In [144]:
import numpy as np

In [145]:
a=np.array([2,3,4])

In [146]:
a

array([2, 3, 4])

In [147]:
a.shape

(3,)

In [148]:
a.dtype

dtype('int32')

In [149]:
b=np.array([1.2,3.5,5.1])

In [150]:
b.dtype

dtype('float64')

In [151]:
b=np.array([(1.5,2,3),(4,5,6),(10,11,12)])

In [152]:
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ],
       [10. , 11. , 12. ]])

In [153]:
b.shape

(3, 3)

In [154]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [155]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [156]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [157]:
b=np.arange(5)

In [158]:
b

array([0, 1, 2, 3, 4])

In [159]:
a.shape

(3,)

In [160]:
a

array([2, 3, 4])

In [161]:
a=np.array([1,2,3,4,5])

In [162]:
a[: :-1]

array([5, 4, 3, 2, 1])

In [163]:
a.shape

(5,)

In [164]:
c=a-b

In [165]:
c

array([1, 1, 1, 1, 1])

In [166]:
b

array([0, 1, 2, 3, 4])

In [167]:
b**2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [168]:
a=np.random.random((2,3))

In [169]:
a

array([[0.47382856, 0.17848377, 0.63329264],
       [0.49442035, 0.68763567, 0.73928611]])

In [170]:
a.sum()

3.2069470946594336

In [171]:
a

array([[0.47382856, 0.17848377, 0.63329264],
       [0.49442035, 0.68763567, 0.73928611]])

In [172]:
a.min()

0.1784837678333412

In [173]:
a.max()

0.7392861086188123

In [174]:
b

array([0, 1, 2, 3, 4])

In [175]:
b=np.arange(12).reshape(3,4)

In [176]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [177]:
a=np.arange(10)**3

In [178]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [179]:
a[2]

8

In [180]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [181]:
a[:6:2]=-1000

In [182]:
a[:6:2]

array([-1000, -1000, -1000], dtype=int32)

In [183]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [184]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [185]:
a[: :-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [186]:
a=np.array([1,2,3,4,5])

In [187]:
a

array([1, 2, 3, 4, 5])

In [188]:
a[: :-1]

array([5, 4, 3, 2, 1])

In [189]:
for i in a:
    print(i**(1/3))

1.0
1.2599210498948732
1.4422495703074083
1.5874010519681994
1.7099759466766968


In [190]:
for i in a:
    print(i**2)

1
4
9
16
25


In [191]:
b=np.arange(12).reshape(3,4)

In [192]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [193]:
a=np.arange(10)**3

In [194]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [195]:
a[2]

8

In [196]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [197]:
def f(x,y):
    return 10*x+y

In [198]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [199]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [200]:
b.sum(axis=1)

array([ 6, 22, 38])

In [201]:
b.min(axis=1)

array([0, 4, 8])

In [202]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [203]:
import numpy

In [204]:
a=numpy.array([3,2,3])

In [205]:
print('print rank 1 array:')

print rank 1 array:


In [206]:
print ("print using their index a[0]=", a[0])

print using their index a[0]= 3


In [207]:
a[0]=5

In [208]:
a

array([5, 2, 3])

In [209]:
print("print the whole array",a)

print the whole array [5 2 3]


In [210]:
b=numpy.array([[10,20,30],[40,50,60]])

In [211]:
print('\nprint rank 2 array')


print rank 2 array


In [212]:
a=numpy.zeros((2,2))

In [213]:
print('\nprint a 2-by-2 zero matrix:\n',a)


print a 2-by-2 zero matrix:
 [[0. 0.]
 [0. 0.]]


In [214]:
b=numpy.ones((2,2))

In [215]:
print('\nprint a 2-by-2 all one matrix:\n',b)


print a 2-by-2 all one matrix:
 [[1. 1.]
 [1. 1.]]


In [216]:
c=numpy.full((3,3),6)

In [217]:
print('\nprint a 3-by-3 constant matrix for value = 6:\n', c)


print a 3-by-3 constant matrix for value = 6:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [218]:
d=numpy.eye(3)

In [219]:
print('\nprint a 3-by-3 identity matrix:\n', d)


print a 3-by-3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [220]:
import numpy

In [221]:
x=numpy.array([[1,2],[3,4]])

In [222]:
y=numpy.array([[3,4],[5,6]], dtype=numpy.float64)

In [223]:
print('X=', x)

X= [[1 2]
 [3 4]]


In [224]:
print('Y= \n ',y)

Y= 
  [[3. 4.]
 [5. 6.]]


In [225]:
print('\nElementwise addition of two matrices: ( X + Y of Matlab)')


Elementwise addition of two matrices: ( X + Y of Matlab)


In [226]:
print('Add using add operator: \n', x + y)

Add using add operator: 
 [[ 4.  6.]
 [ 8. 10.]]


In [227]:
print('Add using add functtion: \n', numpy.add(x,y))

Add using add functtion: 
 [[ 4.  6.]
 [ 8. 10.]]


In [228]:
print('Add using add function: \n', numpy.add(x,y))

Add using add function: 
 [[ 4.  6.]
 [ 8. 10.]]


In [229]:
print('\nElementwise subtraction of two matrices: (X - Y of Matlab)')


Elementwise subtraction of two matrices: (X - Y of Matlab)


In [230]:
print('Subtract using operator: \n', x-y)

Subtract using operator: 
 [[-2. -2.]
 [-2. -2.]]


In [231]:
print ('Subtract using function: \n', numpy.subtract(x,y))

Subtract using function: 
 [[-2. -2.]
 [-2. -2.]]


In [232]:
print('\nElementwise Multiplication of two matrices: (X . * Y of Matlab)')


Elementwise Multiplication of two matrices: (X . * Y of Matlab)


In [233]:
print('Multiply using operator: \n', x*y)

Multiply using operator: 
 [[ 3.  8.]
 [15. 24.]]


In [234]:
print('\nElementwise division of two matrices: ( X ./ Y of Matlab)')


Elementwise division of two matrices: ( X ./ Y of Matlab)


In [235]:
print('Division using operator: \n', x/y)

Division using operator: 
 [[0.33333333 0.5       ]
 [0.6        0.66666667]]


In [236]:
print('Division using function: \n', numpy.divide(x,y))

Division using function: 
 [[0.33333333 0.5       ]
 [0.6        0.66666667]]


In [237]:
print('\nSquare root each element of X matrix\n', numpy.sqrt(x))


Square root each element of X matrix
 [[1.         1.41421356]
 [1.73205081 2.        ]]


In [238]:
print('\nMatrix Multiplication of two matrices: (X * Y of Matlab)')


Matrix Multiplication of two matrices: (X * Y of Matlab)


In [239]:
def f(x,y):
    return 10*x+y

In [240]:
b=np.fromfunction(f,(5,4))

In [241]:
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [242]:
b[2,3]

23.0

In [243]:
b[0:5,1]

array([ 1., 11., 21., 31., 41.])

In [244]:
b[:,1]

array([ 1., 11., 21., 31., 41.])

In [245]:
b[1:3,2]

array([12., 22.])

In [246]:
b.sum(axis=0)

array([100., 105., 110., 115.])

In [247]:
b.min(axis=1)

array([ 0., 10., 20., 30., 40.])

In [248]:
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [249]:
b.cumsum(axis=1)

array([[  0.,   1.,   3.,   6.],
       [ 10.,  21.,  33.,  46.],
       [ 20.,  41.,  63.,  86.],
       [ 30.,  61.,  93., 126.],
       [ 40.,  81., 123., 166.]])

In [250]:
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [251]:
import numpy

In [252]:
a=numpy.array([3,2,3])

In [253]:
a

array([3, 2, 3])

In [254]:
a[0]

3

In [255]:
a[0]=55

In [256]:
a

array([55,  2,  3])

In [257]:
b=numpy.array([[1,2,3],[4,5,6]])

In [258]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [259]:
b[0,0]

1

In [260]:
b[0,1]

2

In [261]:
b[1,2]

6

In [262]:
b[:1,:2]

array([[1, 2]])

In [263]:
a=numpy.zeros((2,2))

In [264]:
a

array([[0., 0.],
       [0., 0.]])

In [265]:
b=numpy.ones((2,2))

In [266]:
b

array([[1., 1.],
       [1., 1.]])

In [267]:
c=numpy.full((3,3),6)

In [268]:
c

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [269]:
d=numpy.eye(3)

In [270]:
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [271]:
import numpy

In [272]:
x=numpy.array([[1,2],[3,4]])

In [273]:
y=numpy.array([[4,5],[6,7]])

In [274]:
x

array([[1, 2],
       [3, 4]])

In [275]:
y

array([[4, 5],
       [6, 7]])

In [276]:
print(a+b)

[[1. 1.]
 [1. 1.]]


In [277]:
print(numpy.add(x,y))

[[ 5  7]
 [ 9 11]]


In [278]:
print(a-b)

[[-1. -1.]
 [-1. -1.]]


In [279]:
print(x-y)

[[-3 -3]
 [-3 -3]]


In [280]:
print(numpy.subtract(x,y))

[[-3 -3]
 [-3 -3]]


In [281]:
print(x*y)

[[ 4 10]
 [18 28]]


In [282]:
print(numpy.multiply(x,y))

[[ 4 10]
 [18 28]]


In [283]:
print(numpy.square(x))

[[ 1  4]
 [ 9 16]]
